modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/fnuecke/oc2r/issues"
license = "MIT"

[[mods]]
modId = "lcjsg"
version = "${file.jarVersion}"
displayName = "Libre Computers and Just Stargate Mod"
authors = "The Realm 18 Studios"
description = '''
Libre Drivers for Just Stargate Mod.
'''

[[dependencies.lcjsg]]
modId = "forge"
mandatory = true
versionRange = "[40.1.68,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.lcjsg]]
modId = "minecraft"
mandatory = true
versionRange = "1.20.1"
ordering = "NONE"
side = "BOTH"

[[dependencies.lcjsg]]
modId = "oc2"
mandatory = true
versionRange = "[1.1.0,)"
side = "BOTH"
ordering = "AFTER"

[[dependencies.lcjsg]]
modId = "jsg"
mandatory = true
versionRange = "[5,)"
side = "BOTH"
ordering = "AFTER"
